### ISSUE TITLE
Modify Batch Processor Run FINISHED  email and attatched file

### ISSUE THREAD

**Issue by mikeadamo1** [duke-libraries/ddr-batch#34]
Modify the [repository-01] Batch Processor Run FINISHED  email and attached details.txt.  It would be helpful if the collection title was included in the subject line and body of the email.  It would also be helpful if the file name of detail.txt attachment and the first line of detail.txt included the collection title.  

This is a non-critical non time sensitive issue.

**Comment by coblej** [comment]
Moved to Jira -- https://duldev.atlassian.net/browse/DDR-1385 .
